# Header
menu:
	Home: /
	Projects: Projects/	
	About: about/

# Profile
profile:
	location: 中國 · 桂林 (GuiLin, China)
	github: xieguigang
	organization: GCModeller.org

#Widget
sidebar: true
navfixed: false

#WidgetText
excerpt_link: 繼續閱讀

#Github(请务必配置github帐号)
github:
  popular_repos: ['VisualBasic_AppFramework','GCModeller','GNUplot', 'ManhattanPlot']
  contribute_repos: ['SMRUCC/GCModeller']

#Comments
comments:
	duoshuo_username: 

#Source Code
source_code: https://github.com/xieguigang/xieguigang.github.io-hexo
