-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 19:23:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lychee_simple
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lychee_simple
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lychee_simple` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `lychee_simple` ;

-- -----------------------------------------------------
-- Table `lychee_simple`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee_simple`.`album` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lychee_simple`.`album` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `photos` INT UNSIGNED NOT NULL DEFAULT 0,
  `parent_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  `config_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lychee_simple`.`labels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee_simple`.`labels` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lychee_simple`.`labels` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NOT NULL,
  `category` INT UNSIGNED NOT NULL,
  `description` MEDIUMTEXT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lychee_simple`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee_simple`.`photo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lychee_simple`.`photo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `config_id` INT UNSIGNED NULL,
  `raw` VARCHAR(255) NOT NULL,
  `large` VARCHAR(255) NOT NULL,
  `thumbnail` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `exif` MEDIUMTEXT NULL COMMENT 'json of the exif metadata',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lychee_simple`.`photo_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee_simple`.`photo_groups` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lychee_simple`.`photo_groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo_id` INT UNSIGNED NOT NULL,
  `album_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lychee_simple`.`photo_labels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee_simple`.`photo_labels` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lychee_simple`.`photo_labels` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo_id` INT UNSIGNED NOT NULL,
  `label_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lychee_simple`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee_simple`.`settings` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lychee_simple`.`settings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `configs` MEDIUMTEXT NOT NULL COMMENT 'config json or plain text',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
