-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 19:00:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lychee
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lychee` ;

-- -----------------------------------------------------
-- Schema lychee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lychee` DEFAULT CHARACTER SET utf8 ;
USE `lychee` ;

-- -----------------------------------------------------
-- Table `lychee`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`album` ;

CREATE TABLE IF NOT EXISTS `lychee`.`album` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `guid` CHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `photos` INT UNSIGNED NOT NULL DEFAULT 0,
  `parent_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  `config_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC) VISIBLE,
  CONSTRAINT `parent_folder`
    FOREIGN KEY (`parent_id`)
    REFERENCES `lychee`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `settings`
    FOREIGN KEY (`config_id`)
    REFERENCES `lychee`.`settings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lychee`.`labels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`labels` ;

CREATE TABLE IF NOT EXISTS `lychee`.`labels` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NOT NULL,
  `category` INT UNSIGNED NOT NULL,
  `description` MEDIUMTEXT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `parent_label`
    FOREIGN KEY (`category`)
    REFERENCES `lychee`.`labels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lychee`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`photo` ;

CREATE TABLE IF NOT EXISTS `lychee`.`photo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `guid` CHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `config_id` INT UNSIGNED NULL,
  `raw` VARCHAR(255) NOT NULL,
  `large` VARCHAR(255) NOT NULL,
  `thumbnail` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `exif` MEDIUMTEXT NULL COMMENT 'json of the exif metadata',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC) VISIBLE,
  CONSTRAINT `settings`
    FOREIGN KEY (`config_id`)
    REFERENCES `lychee`.`settings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lychee`.`photo_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`photo_groups` ;

CREATE TABLE IF NOT EXISTS `lychee`.`photo_groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo_id` INT UNSIGNED NOT NULL,
  `album_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `photo_data`
    FOREIGN KEY (`photo_id`)
    REFERENCES `lychee`.`photo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `album_data`
    FOREIGN KEY (`album_id`)
    REFERENCES `lychee`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lychee`.`photo_labels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`photo_labels` ;

CREATE TABLE IF NOT EXISTS `lychee`.`photo_labels` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo_id` INT UNSIGNED NOT NULL,
  `label_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `photo_source`
    FOREIGN KEY (`photo_id`)
    REFERENCES `lychee`.`photo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `label_tag`
    FOREIGN KEY (`label_id`)
    REFERENCES `lychee`.`labels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lychee`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`settings` ;

CREATE TABLE IF NOT EXISTS `lychee`.`settings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `configs` MEDIUMTEXT NOT NULL COMMENT 'config json or plain text',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
