-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 01:58:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lychee
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lychee` ;

-- -----------------------------------------------------
-- Schema lychee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lychee` DEFAULT CHARACTER SET utf8 ;
USE `lychee` ;

-- -----------------------------------------------------
-- Table `lychee`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`album` ;

CREATE TABLE IF NOT EXISTS `lychee`.`album` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `photos` INT UNSIGNED NOT NULL DEFAULT 0,
  `parent_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  `config_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `parent_folder`
    FOREIGN KEY (`parent_id`)
    REFERENCES `lychee`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `settings`
    FOREIGN KEY (`config_id`)
    REFERENCES `lychee`.`settings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lychee`.`exif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`exif` ;

CREATE TABLE IF NOT EXISTS `lychee`.`exif` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `photo_source`
    FOREIGN KEY (`photo_id`)
    REFERENCES `lychee`.`photo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lychee`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`photo` ;

CREATE TABLE IF NOT EXISTS `lychee`.`photo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `config_id` INT UNSIGNED NULL,
  `raw` VARCHAR(255) NOT NULL,
  `large` VARCHAR(255) NOT NULL,
  `thumbnail` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `settings`
    FOREIGN KEY (`config_id`)
    REFERENCES `lychee`.`settings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lychee`.`photo_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`photo_groups` ;

CREATE TABLE IF NOT EXISTS `lychee`.`photo_groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo_id` INT UNSIGNED NOT NULL,
  `album_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `photo_data`
    FOREIGN KEY (`photo_id`)
    REFERENCES `lychee`.`photo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `album_data`
    FOREIGN KEY (`album_id`)
    REFERENCES `lychee`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lychee`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lychee`.`settings` ;

CREATE TABLE IF NOT EXISTS `lychee`.`settings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `configs` MEDIUMTEXT NOT NULL COMMENT 'config json',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
